version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: SomeSecretPassword
      POSTGRES_DB: mydb
      PGDATA: /data/postgres
    volumes:
      - ./database:/data/postgres
    ports:
      - "5432:5432"
  cerbos:
    image: 'ghcr.io/cerbos/cerbos:latest'
    ports:
      - '3593:3593'
      - '3592:3592'
    volumes:
      - './cerbos:/settings'
    command: server --config=/settings/conf.yaml
