version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: SomeSecretPassword
      POSTGRES_DB: mydb
      PGDATA: /data/postgres
    volumes:
      - ./database:/data/postgres
    ports:
      - "5432:5432"
